import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";
import Header from "../components/layout/header/header";

const lexend = Lexend({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Selamat datang di stunting.id",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lexend.className}>
        <div className="w-full max-w-[1500px] mx-auto px-4 sm:px-10">
          <Header />
          <div className="pt-5">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
